/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-106539-g49526852c3-20220408"
#endif /* AVUTIL_FFVERSION_H */
